### ISSUE TITLE
Unable to create Kinect runtime Traceback

### ISSUE THREAD

**Issue by Ferreronico** [shrirangakadam007/pykinect3.6#4]
Hello,
I can't run the code while I follow the instruction, and this line can't be runned : kinect = nui.Runtime()

And I have this error: 

KinectError: Unable to create Kinect runtime Traceback (most recent call last):
  File "C:\Users\N\Anaconda3\lib\site-packages\pykinect\nui\__init__.py", line 117, in __init__
    self._nui.NuiInitialize(nui_init_flags)
  File "C:\Users\N\Anaconda3\lib\site-packages\pykinect\nui\_interop.py", line 168, in NuiInitialize
    _NuiInstance._NuiInitialize(self, dwFlags)
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2097085825] Windows Error 0x8301027f

Do someone has an idea ?

**Comment by Ferreronico** [comment]
My bad, if someone has this problem you need to properly connect the Kinect and be sure it works. (you can test with a game from the kinect development toolkit)
